### ISSUE TITLE
cannot spawn git-xltrail-diff.exe when running Git bash from Sourcetree

### ISSUE THREAD

**Issue by Dripdrop12** [ZoomerAnalytics/git-xltrail#18]
I am getting the following error when trying to run `git diff` from git bash started from within Source Tree:

```
error: cannot spawn git-xltrail-diff.exe: No such file or directory
fatal: external diff died, stopping at *.xlam
```

**Comment by fzumstein** [comment]
Are you starting git bash by clicking on the `Terminal` button at the top right and then you type in `git diff` manually? If so, I couldn't replicate the issue - what versions of Git (`git --version`) and SourceTree are you running?
From your description it sounds like if you start Git bash outside of SourceTree, then it works? Can you compare the output `env|grep PATH` in both instances? does `GIT_XLTRAIL_PATH=C:\Program Files\Git xltrail` and `PATH=.../c/Program Files/Git xltrail/...` show up when started from within SourceTree?

**Comment by fzumstein** [comment]
@Dripdrop12 Any update on this?

**Comment by Dripdrop12** [comment]
We can close it out. It was related to an internal security rule
