### ISSUE TITLE
Unexpected Number of arguments while running git-xltrail-diff

### ISSUE THREAD

**Issue by engineermanmohansingh** [ZoomerAnalytics/git-xltrail#26]
While performing diff using the `git-xltrail-diff` command in the working directory, A message appears **Unexpected Number of arguments**  How many arguments does this command needs?

**Comment by bstiel** [comment]
did you directly invoke `git-xltrail-diff`? 
the correct way is to just use `git diff` and let git invoke `git-xltrail-diff` under the hood. You don't need to worry about the lower-level commands.
Can you please confirm (or copy/paste your command line in-/output here)?

**Comment by bstiel** [comment]
Closing this as there is no response. Feel free to reopen.
