### ISSUE TITLE
add support for docm etc.

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/git-xltrail#8]

**Comment by quassy** [comment]
This being closed, does this mean xltrail already has support for docs? That'd be great!

**Comment by fzumstein** [comment]
Hey @quassy, we supported it in one of the earlier versions but then took a decision to add advanced features for Excel rather than making this a broad office integration. This required us to change the underlying engine and the new one does not support word files anymore. So, unfortunately, no support for anything else than Excel files going forward.
